overview:
  title: Product Configurator
  image: logo.png
  description: This configurator shows how alpha channels are used.
  facts:
    - Dynamic Single Source Imaging
    - Alpha Channels
    - Effect Usage
  order: 5
sample:
  template:
    schema: bootstrap-taupe
    components:
      menu:
        template: data/clothing-menu.yml
      featured:
        template: data/clothing-featured.yml
      footer:
        credits:
          photos:
            - author: Artem Bondarchuk
              link: https://unsplash.com/@artembondarchuk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText
              platform: Unsplash
          viewer:
            link: https://www.neptunelabs.com/dynamic-imaging/
      bootstrap:
        icons: true

