overview:
  title: Product Configurator
  image: logo.png
  description: A configurator shows how alpha channels can be used.
  order: 5
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/clothing-menu.yml
      featured:
        template: data/clothing-featured.yml
      footer: true
      fsi:
        touchZoom: true
      bootstrap:
        icons: true
  mapping:
    html: 'index.html'
    css: 'config.css'
    js: 'config.js'
jsfiddle:
  deploy: true
