overview:
  title: Product Listing Page (PLP)
  image: logo.png
  description: Shows how a product listing page with dynamic imaging used looks.
  facts:
    - Dynamic Single Source Imaging
    - Overlays
    - Crop Effect
  order: 2
schema: bootstrap-taupe
sample:
  menu:
    data: furniture-menu.yml
  hero:
    url: /server?type=image&source=images/samples/ssi/furniture/tv-cabinet-6185020.jpg&width=1903&rect=0.08146,0.53855,0.85105,0.21963
    height: 30vh
  categories: true
  footer:
    credits:
      photos:
        author: various artists
        link: https://pixabay.com/
        platform: Pixabay
      viewer:
        link: https://www.neptunelabs.com/dynamic-imaging/
  bootstrap:
    icons: false
