name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JSFIDDLE_REPO: neptunelabs/fsi-jsfiddle-samples

jobs:

  publish-jsfiddle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: check jsfiddle version with package
        run: |
          npm install
          npm run
          node ./node_modules/@neptunelabs/fsi-samples-framework/jsfiddle-builder.js
